config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#   get 'lists' => 'lists#index'
#   get 'lists/new' => 'lists#new', as: :new_list
#   get 'lists/:id' => 'lists#show', as: :list
#   post 'lists' => 'lists#create' do
#     get 'lists/:id/bookmarks/new', to: 'lists#bookmarks#new', as: :new_list_bookmark
#     post 'lists/:id/bookmarks', to: 'lists#bookmarks#create'
#   end
# end
  root to: 'lists#index'
  resources :lists, except: [ :edit, :update, :destroy ] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: :create
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(params_bookmark)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.destroy(params[:id])
    redirect_to lists_path
  end

  private

  def params_bookmark
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save
      redirect_to list_path(@list)
    else
      render new_list_path
    end
  end

  private

  def params_list
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :list %>
  <%= f.association :movie %>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
<h1><%= list.name %></h1>
<%= link_to "See #{list.name}", list_path(list) %>
<% end %>

<p><%= link_to "Create a new list", new_list_path %></p>

app/views/lists/new.html.erb
<%= simple_form_for [ @list ] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li><h2><%= bookmark.movie.title %></h2></li>
    <li><img src=<%= bookmark.movie.poster_url %> alt="j'ai eut réson" width="350"></li>
    <li><h2><%= bookmark.comment %></h2></li>
  <% end %>
</ul>




<p><%= link_to "Create a bookmark", new_list_bookmark_path(@list) %></p>